# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frefresh < Formula
  desc "Interactive CLI for refreshing tables in Fabric semantic models"
  homepage "https://github.com/DanielAndreassen97/frefresh"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DanielAndreassen97/frefresh/releases/download/v1.0.0/frefresh_darwin_amd64.tar.gz"
      sha256 "d632edfa4eb465a1b4e12c5700b6975135a5f699414d9bb9f80b24e4b1665275"

      define_method(:install) do
        bin.install "frefresh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DanielAndreassen97/frefresh/releases/download/v1.0.0/frefresh_darwin_arm64.tar.gz"
      sha256 "a0ed0a541d378e4860e13d528e2e61eb3b4fa2f1612165c4701f765834adf0b8"

      define_method(:install) do
        bin.install "frefresh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DanielAndreassen97/frefresh/releases/download/v1.0.0/frefresh_linux_amd64.tar.gz"
      sha256 "43487447ba8ed572cbf70616079d345cbe84d220f15dfd83977a5baf81105bc3"
      define_method(:install) do
        bin.install "frefresh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DanielAndreassen97/frefresh/releases/download/v1.0.0/frefresh_linux_arm64.tar.gz"
      sha256 "0feb1ebf55c69f34272f46e49affc4bdc2ad0fa43ade6504fbda3258a87c8b2d"
      define_method(:install) do
        bin.install "frefresh"
      end
    end
  end
end
