# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frefresh < Formula
  desc "Interactive CLI for refreshing tables in Fabric semantic models"
  homepage "https://github.com/DanielAndreassen97/frefresh"
  version "1.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DanielAndreassen97/frefresh/releases/download/v1.2.1/frefresh_darwin_amd64.tar.gz"
      sha256 "b3fbbe6d7f8c697d06ed598316d64d56e13402f7c76dff791886e018af928a7e"

      define_method(:install) do
        bin.install "frefresh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DanielAndreassen97/frefresh/releases/download/v1.2.1/frefresh_darwin_arm64.tar.gz"
      sha256 "51464c8d6dd01ebf02cf2e0f29bef79c333c3237040dfd469a9f6063ec92508c"

      define_method(:install) do
        bin.install "frefresh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DanielAndreassen97/frefresh/releases/download/v1.2.1/frefresh_linux_amd64.tar.gz"
      sha256 "90fefd803acd5220393cd29fa3b67f5f2d2dfff90ab67a3e3cde661bf1116506"
      define_method(:install) do
        bin.install "frefresh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DanielAndreassen97/frefresh/releases/download/v1.2.1/frefresh_linux_arm64.tar.gz"
      sha256 "2ba12c48bed2e5e04c338aef88df608b1ccbaa55a5dde402adc5fa05cc54e898"
      define_method(:install) do
        bin.install "frefresh"
      end
    end
  end
end
