# This file was generated by GoReleaser. DO NOT EDIT.
cask "frefresh" do
  name "frefresh"
  desc "Interactive CLI for refreshing tables in Fabric semantic models"
  homepage "https://github.com/DanielAndreassen97/frefresh"
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "frefresh"

  on_macos do
    on_intel do
      url "https://github.com/DanielAndreassen97/frefresh/releases/download/v#{version}/frefresh_darwin_amd64.tar.gz"
      sha256 "472647ea2dfd8e17fc262b6663ed995cac20eb20c02bd899332d94d866cb8f66"
    end
    on_arm do
      url "https://github.com/DanielAndreassen97/frefresh/releases/download/v#{version}/frefresh_darwin_arm64.tar.gz"
      sha256 "eba953d59106b740288f304f49fbcd601f84ff71659bcf91164686782b61cb44"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DanielAndreassen97/frefresh/releases/download/v#{version}/frefresh_linux_amd64.tar.gz"
      sha256 "a04ff817c809822b407c3560731070ca8bbc6c71bf9db6afbe5de265da121c8d"
    end
    on_arm do
      url "https://github.com/DanielAndreassen97/frefresh/releases/download/v#{version}/frefresh_linux_arm64.tar.gz"
      sha256 "920aec270b6d152c1e9c467e6a6907fd4460e15b5e65c41daad81d652d3ec16f"
    end
  end

  # No zap stanza required
end
