# This file was generated by GoReleaser. DO NOT EDIT.
cask "frefresh" do
  name "frefresh"
  desc "Interactive CLI for refreshing tables in Fabric semantic models"
  homepage "https://github.com/DanielAndreassen97/frefresh"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "frefresh"

  on_macos do
    on_intel do
      url "https://github.com/DanielAndreassen97/frefresh/releases/download/v#{version}/frefresh_darwin_amd64.tar.gz"
      sha256 "54323aba67a06150e2cc19831b3e35323180df04c8d6df4b8084ce65a8839d83"
    end
    on_arm do
      url "https://github.com/DanielAndreassen97/frefresh/releases/download/v#{version}/frefresh_darwin_arm64.tar.gz"
      sha256 "ed1e9b9db698edd3ee3199c7783fa9a887f6e845425d2e633faa0e36834b0e77"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DanielAndreassen97/frefresh/releases/download/v#{version}/frefresh_linux_amd64.tar.gz"
      sha256 "9dbd9e8331a30ddaf79257a7bf4d34893dcec7de41f34dd9829d696bf4cbff58"
    end
    on_arm do
      url "https://github.com/DanielAndreassen97/frefresh/releases/download/v#{version}/frefresh_linux_arm64.tar.gz"
      sha256 "c5535bdead592337cbd4e55b57ff387a110d2fd6f29b67275e5b305eb34ca051"
    end
  end

  # No zap stanza required
end
